version: '3'
services:
  redis-api:
    image: redis:6.2.6
    container_name: redis-api
    env_file: ./.env
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    #hostname: redis
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
      #- "6379:6379"
    volumes:
      - ./Redis:/var/lib/postgresql/data
    expose:
      - $REDIS_LOCAL_PORT
    networks:
      - api-prod
  api:
    container_name: api
    build:
      context: './api'
      dockerfile: Dockerfile-Prod
    env_file: ./.env
    command: python /code/server.py
    environment:
      - REDIS_PORT=$REDIS_DOCKER_PORT
      - REDIS_HOST_NAME=$API_REDIS_HOST
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - API_PORT=$API_DOCKER_PORT
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    expose:
      - $API_LOCAL_PORT
    volumes:
    - ./api:/code
    depends_on:
      - redis-api
    networks:
      - api-prod

volumes:
  Redis:
networks:
  api-prod:
    driver: bridge